server:
  port: 8001
spring:
  datasource:
    primary:
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/springboot?useSSL=false&characterEncoding=UTF8
    secondary:
      username: hr
      password: hr
      driver-class-name: oracle.jdbc.OracleDriver
      url: jdbc:oracle:thin:@localhost:1521:FROGTECH
debug: true
