server:
  port: 8001
spring:
  application:
    name: springboot-redis
#  redis:
#    host: 192.168.1.192   #默认：localhost
#    port: 6379            #默认：6379
#    password: 123456
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.1.192:3306/springboot?useSSL=false
    username: root
    password: root
  jpa:
    show-sql: true
  #Redis集群哨兵模式
  redis:
    password: 123456
    sentinel:
      nodes: 192.168.1.192:26379,192.168.1.192:26479,192.168.1.192:26579
      master: mymaster
