spring:
  application:
    name: tx-chain
  datasource:
    primary:
      username: root
      password: root
      url: jdbc:mysql://localhost:3306/springboot?useSSL=false&characterEncoding=utf8
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
    secondary:
      username: hr
      password: hr
      url: jdbc:oracle:thin:@localhost:1521:FROGTECH
      driver-class-name: oracle.jdbc.OracleDriver
      type: com.alibaba.druid.pool.DruidDataSource
server:
  port: 8001
debug: true
logging:
  level: debug